#!/bin/zsh
# This script defines a function for generating a prompt
# of the format ipv4 address | localhost that can be included in a custom prompt

if [[ -z "$ip_prompt_file_sourced" ]]; then
    # You can access the prompt generated by this script with the IP_PROMPT env variable
    # Configuration variables
    #   SHOW_IP: Set to 1 for IP_PROMPT to show ip address, otherwise will show localhost
    # Exported variables
    #   IP: Current ipv4 address
    #   IP_PROMPT: Custom prompt that will either display the ip address or localhost
    ip_prompt() {    
        if [[ "$OSTYPE" == "darwin"* ]]; then
            IP=$(ipconfig getifaddr en0)
        else
            IP=$(ip -4 address show eth0 | grep -oP 'inet \K[\d.]+')
        fi
        if [ "$SHOW_IP" = true ]; then
            IP_PROMPT=$IP
        else
            IP_PROMPT="localhost"
        fi
    }

    sip() {
        export SHOW_IP=true
        save_vars
    }

    hip(){
        export SHOW_IP=false
        save_vars
    }

    # Used to setup pathing
    # Do not remove or script will not know how to find other scripts
    declare -A zsh_scripts_directories
    if [ -n "$ZSH_VERSION" ]; then
        zsh_scripts_directories["ip_scripts_dir"]=$(dirname "${(%):-%x}")
    elif [ -n "$BASH_VERSION" ]; then
        zsh_scripts_directories["ip_scripts_dir"]=$(dirname "${BASH_SOURCE[0]}")
    fi

    source "$(dirname "${zsh_scripts_directories["ip_scripts_dir"]}")/shared/shared-scripts.sh"

    export SHOW_IP=false
    add_var "SHOW_IP"
    load_vars
fi

ip_prompt_file_sourced=true