#!/bin/zsh
# This script defines a function for generating a prompt
# of the format rvm(ruby-version) that can be included in a custom prompt

if [[ -z "$rvm_prompt_file_sourced" ]]; then
    # You can access the prompt generated by this script with the RVM_PROMPT env variable
    rvm_prompt() {
        # Current virtualenv
        local ref=$(rvm-prompt)
        if [[ -n "$ref" ]]; then
            RVM_PROMPT='rvm(%F{cyan}'${ref##*/}'%f)'
        else
            RVM_PROMPT=''
        fi
    }

    rvm_prompt_set_newline() { 
        rvm_prompt_newlines_before=$1
        rvm_prompt_newlines_after=$2
    }

    rvm_prompt_newline() {
        rvm_prompt

        local countBefore=$rvm_prompt_newlines_before
        local countAfter=$rvm_prompt_newlines_after
        newLinesBefore=''
        newLinesAfter=''

        if [[ "$OSTYPE" == "darwin"* ]]; then
            if (($countBefore > 0)); then
                for i in $(seq 1 $countBefore); do
                    newLinesBefore=$newLinesBefore$'%{\n%}'
                done           
            fi        
            if (($countAfter > 0)); then
                for j in $(seq 1 $countAfter); do
                    newLinesAfter=$newLinesAfter$'%{\n%}'
                done
            fi
        else
            for i in $(seq 1 $countBefore); do
                newLinesBefore=$newLinesBefore$'%{\n\r%}'
            done
            for j in $(seq 1 $countAfter); do
                newLinesAfter=$newLinesAfter$'%{\n\r%}'
            done
        fi

        if [ -n "$RVM_PROMPT" ]; then
            RVM_PROMPT=$newLinesBefore$RVM_PROMPT$newLinesAfter
        fi
    }
fi

rvm_prompt_file_sourced=true;